Support setting failmode on pools
illumos/image-builder pull request #6
Opened 2023-06-06 12:09 UTC by citrus-it

2023-06-08 10:53 UTC, citrus-it commented
With this configuration:

```
    "pool": {
        "name": "rpool",
        "bename": "ramdisk",
        "ashift": 9,
        "uefi": false,
        "size": 800,
        "label": false,
        "no_features": false,
        "compression": "gzip-9",
        "autoexpand": true,
        "options": ["failmode=panic"],
        "fsoptions": ["primarycache=metadata"]
    },
```

I see the appropriate options being passed to `zpool`:

```
Jun 08 10:48:06.004 INFO O| Jun 08 10:48:06.004 INFO exec: ["/sbin/zpool", "create", "-t", "TEMPORARY-gimlet-zfs", "-O", "compression=gzip-9", "-R", "/rpool/images/andy/work/gimlet/zfs/altroot", "-o", "ashift=9", "-o", "autoexpand=on", "-o", "failmode=panic", "-O", "primarycache=metadata", "rpool", "/dev/dsk/c5t1d0p0"]
```

I also tested with a template which did not include `options` or `fsoptions` in the pool definition, and it worked correctly:

```
Jun 08 10:52:59.005 INFO O| Jun 08 10:52:59.004 INFO exec: ["/sbin/zpool", "create", "-t", "TEMPORARY-gimlet-zfs", "-O", "compression=gzip-9", "-R", "/rpool/images/andy/work/gimlet/zfs/altroot", "-o", "ashift=9", "-o", "autoexpand=on", "rpool", "/dev/dsk/c5t1d0p0"]
```

2023-06-15 19:00 UTC, jclulow requested changes
This seems a reasonable addition to the interface!  A few minor notes.

2023-06-15 19:00 UTC, jclulow commented on src/main.rs
> +    options: Option<Vec<String>>,
Rather than `Option<Vec<_>>` I'd probably do:

```rust
#[serde(default)]
options: Vec<String>,
```

Then I believe `options` will just be empty if it is not specified.

2023-06-15 19:00 UTC, jclulow commented on src/main.rs
> +    }
I think we should probably do macro expansion on these arguments as we're pushing them in here; e.g.,

```rust
args.push(ib.expand(&o)?);
```

That way one could allow for, say, `failmode`, to be passed in via features; e.g.., `-F failmode=panic`.

2023-06-15 22:20 UTC, citrus-it commented on src/main.rs
> +    options: Option<Vec<String>>,
Done.

2023-06-15 22:21 UTC, citrus-it commented on src/main.rs
> +    }
Oh yes, nice idea. It was a bit more complicated due to lifetimes, but I've done this and tested that the expansion works.

2023-06-15 22:25 UTC, citrus-it commented
re-based back on main after the trim change went in.

2023-06-16 20:53 UTC, merged

2023-06-16 20:53 UTC, jclulow commented
Thanks for the changes!